### ISSUE TITLE
Update project README and Quickstart with new download URL

### ISSUE THREAD

**Issue by oubiwann** [lfe-deprecated/lfetool#109]

**Comment by ghost** [comment]
The makefile created by `lfetool` (`resources/make/common.mk`) also contains a link to the old version.

The command `lfetool update` in version `1.2.0` will also pull the old version `1.0.1` and overwrite the installed `1.2.0`.

**Comment by oubiwann** [comment]
Thanks for the bug report! I'll create a new ticket for this.

**Comment by oubiwann** [comment]
Created ticket #113 to adjust the code (vs. the docs for this ticket).

**Comment by oubiwann** [comment]
This was fixed a while ago ... git blame says on 2014-10-16.

Thanks @dokkarr!
