### ISSUE TITLE
Add support for brew base64 on Mac OS X

### ISSUE THREAD

**Issue by oubiwann** [lfe-deprecated/lfetool#110]
From an IRC comment/feedback:

```
<strg> oh. btw. I had some problems with the base64 command in lfetool.
           On OSX it is a special case in the script because the base64
           option -d is -D. But I use homebrew and had the coreutils
           bottle installed (for better ls etc.) and that one has a base64
           too, but with the -d option. Maybe if the script would use
           '/usr/bin/base64' explicitly on Darwin?
```

**Comment by ghost** [comment]
Ok, a bit more context: When you install the `coreutils` package the GNU commands contained therein are linked with a `g` prefix. So the command is actually `gbase64`, which should not be a problem. But the homebrew package info of `coreutils` also states

```
If you really need to use these commands with their normal names, you
can add a "gnubin" directory to your PATH from your bashrc like:

    PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
```

Thats what I did. So a normal install does not clash with the system version of `base64`.

**Comment by oubiwann** [comment]
Thanks for the very helpful update!

Just added a "documentation" label for this one so that it _might_ be easier for folks to find when using homebrew's base64 on Mac.
