### ISSUE TITLE
Update rebar.config files to use the newest versions of the deps

### ISSUE THREAD

**Issue by oubiwann** [lfe-deprecated/lfetool#116]
The following tickets will be adjusting the version of LFE used in their respective projects:
- https://github.com/lfex/lutil/issues/3
- https://github.com/lfex/ltest/issues/5

They will also be bumping the minor version numbers for their respective projects. lfetool v1.3 will need to update its `rebar.config` files to point to these new versions.

This is in support of the tasks outlined in ticket #111.

**Comment by dokkarr** [comment]
The lfetool YAWS plugin has also had its rebar.config.tmpl updated to point to the latest exemplar tag (before that, it was doing the same hanging thing that the others were doing).

**Comment by dokkarr** [comment]
Done.
