### ISSUE TITLE
Update .travis.yaml.tmpl files to include Ubuntu deps

### ISSUE THREAD

**Issue by odacoder** [lfe-deprecated/lfetool#122]
The .travis.yaml template files need to include the following entry, which is required to build YAWS:

``` yaml
before_install:
  - sudo apt-get install libpam0g-dev
```

**Comment by oubiwann** [comment]
That last commit was the fix, but needs to be tested on a generated yaws project that gets uploaded to travis. I'll keep this ticket open until someone has a chance to test and confirm this working for lfetool 1.5.0-dev.

**Comment by oubiwann** [comment]
I'm just going to close this; we can re-open if it didn't work.
