### ISSUE TITLE
'make shell' error in new service project

### ISSUE THREAD

**Issue by darth10** [lfe-deprecated/lfetool#29]
I tried running the repl in a new service project, and I get the following error.
Any clue would be really helpful. 

```
> make shell                                                                                                    ruby-2.1.0 [54/1393]
Getting dependencies ...
==> lfe (get-deps)
==> lfeunit (get-deps)
==> lfe-utils (get-deps)
==> rebar (get-deps)
==> lfe-sample-rebar-plugin (get-deps)
==> my-service (get-deps)
Updating dependencies ...

        Updating ./deps/lfe ...

Already up-to-date.

        Updating ./deps/lfe-sample-rebar-plugin ...

Already up-to-date.

        Updating ./deps/lfeunit ...

Already up-to-date.

        Updating ./deps/lfe-utils ...

Already up-to-date.

        Updating ./deps/rebar ...

Already up-to-date.
Cleaning ebin dir ...
Compiling project code and dependencies ...
==> lfe (compile)
==> lfeunit (compile)
==> lfe-utils (compile)
==> rebar (compile)
==> lfe-sample-rebar-plugin (compile)
==> my-service (compile)
Compiled src/my-service-app.lfe
Compiled src/my-service-sup.lfe
Compiled src/my-service-server.lfe
Starting shell ...

Unknown context: 'repl'

Script: lfetool, v

Usage: /home/darth10/bin/lfetool <command> <context> [<arg> | <context command> <arg>] | <options>


```

**Comment by oubiwann** [comment]
Oh dear! Thanks for the bug report; looking into it now ...

**Comment by oubiwann** [comment]
This looks like an error in a slightly out-of-date `lfetool` script. Hang tight; a new one should be pushed up in a few hours.

**Comment by oubiwann** [comment]
Try again now... there were several issues, including curl not following an HTTP 301 that github recently started returning for content at raw.github.com.

Not sure if the version of lfetool you have will work for an update, but you can try that first:

``` bash
$ lfetool update
```

If that doesn't work, just download the following:
- https://raw.githubusercontent.com/lfe/lfetool/master/lfetool

And then move that to `/usr/local/bin`.

Let me know how it goes...

**Comment by darth10** [comment]
Thanks for the update! :+1: 
Will let you know if it worked soon.

**Comment by darth10** [comment]
Works like a charm! Thank you once again! :smile:

**Comment by oubiwann** [comment]
No problem :-) Thanks again for the report!
