### ISSUE TITLE
Cygwin changes causing problems with test runner

### ISSUE THREAD

**Issue by oubiwann** [lfe-deprecated/lfetool#30]
With pull request #26, I started getting unit test runs that look like this:

``` bash
------------------
Running unit tests ...
------------------
expr: not a decimal number: '      56'
bash: line 548: [: : integer expression expected
expr: not a decimal number: '      46'
bash: line 548: [: : integer expression expected
expr: not a decimal number: '      51'
bash: line 548: [: : integer expression expected
expr: not a decimal number: '      60'
bash: line 548: [: : integer expression expected
expr: not a decimal number: '      32'
bash: line 548: [: : integer expression expected
expr: not a decimal number: '      62'
bash: line 548: [: : integer expression expected
expr: not a decimal number: '      35'
bash: line 548: [: : integer expression expected
expr: not a decimal number: '      33'
bash: line 548: [: : integer expression expected
expr: not a decimal number: '      56'
bash: line 548: [: : integer expression expected
expr: not a decimal number: '      38'
bash: line 548: [: : integer expression expected
======================== EUnit ========================
```

**Comment by oubiwann** [comment]
@redpine50

So I've looked into this more, and I got was able to remove the white space created by `wc -m` with `tr -d ' '`. However, there's now an error with using `expr` to get substrings. For instance, this fails on Mac OS X:

``` bash
$ expr substr apple 1 3
expr: syntax error
```

That's how it's being called in `lfetool` now ...

**Comment by oubiwann** [comment]
Yeah, `expr` on Mac OS X is BSD, not GNU. GNU supports things like `expr index`, `expr length`, and `expr substr`. Not BSD.

I've updated the `dots` variable to be generated without `expr`, and it works now.

**Comment by oubiwann** [comment]
Fixed in b0c2abac02ded01ccaaffc803ed860474e51edc5.

**Comment by redpine50** [comment]
Sorry for pointing wrong direction, I've not seen the Apple OS X box.

Substring using printf command will not work with non-GNU printf.
Most portable way to substring in shell script is using cut command.
So, 

```
dots=`echo "$pad" | cut -c 1-$len`
```

will work on any Unix-like env.

**Comment by oubiwann** [comment]
No worries! The code you had commented out worked great; I'm assuming it works on Cygwin. If not, I can update to use your suggestions above.

Thanks again for the extended support to Windows!
