### ISSUE TITLE
Version 2: figure out new architecture

### ISSUE THREAD

**Issue by oubiwann** [lfe-deprecated/lfetool#47]
The initial plan is to:
1. have a fairly small (relatively) `lfetool` shell script which
2. calls to `lfe` which
3. gets passed parameters which represent commands, subcommands, options, etc., and
4. these are mapped to modules/functions which, in turn, get called

This needs to be explored with:
- a basic shell script and
- some sample modules

In addition to this flow, another one needs to be supported: bootstrapping. The plan here is to:
1. check for a local lfetool install
2. if it doesn't exist, clone to `~/.lfetool/lib` (note that the directory `./lfetool` itself will be used for configuration files, user overrides, etc.)
3. run all commands with `ERL_LIBS=~/.lfetool/lib:$ERL_LIBS` to pick up lfetool modules

**Comment by oubiwann** [comment]
Okay, got the very basics in place with commit 7c0a1c48d7441dca5db0f96d0e9950a79527288f. This doesn't do dispatching, but it does have a simple shell script (which calls `erl` which calls `lfetool:eval`). Next up: 
- dispatching
- deciding on a plugin module namespace
- figuring out where to store templates and how to load them

**Comment by oubiwann** [comment]
Update for the previous comment's bullet points:

I think I've settled on a plugin namespace, one to be used for both official plugins and user-created plugins : `lfetool-plugin-<plugin name>.lfe`, living either:
-  in lfetool's `./plugins/<plugin name>/` directory, or
-  in the user dir `~/.lfetool/plugins/<plugin name>/`

I've created a plugin compiler function in d803117. With this done, I should now be able to test dispatching to a plugin module + function.

Templates will likely stay where they are (version 1.0), in the `plugins/<plugin name>/templates` directory.

**Comment by oubiwann** [comment]
Dispatch is now working (very early version); committed in ac009df (subsequent commits updated output, formatting, etc..

Example usage:

``` bash
$ ./bin/lfetool2 new script fibo
```

This calls the function `new` with argument `fibo` in the module whose name is `lfetool-plugin-script.lfe`. For now, this gives the following output:

``` cl
#(ok
  #(msg "pretending to create new script ...")
  #(script-name fibo)
  #(location "/Users/oubiwann/Dropbox/lab/erlang/lfetool")
  #(cwd "/Users/oubiwann/lab/erlang/los"))
```

With this commit, the basic architecture is vetted. No doubt, more complicated plugins will require adjustments...

**Comment by oubiwann** [comment]
Actually, there is one more thing to do:
- figure out the mechanics of file templates, which includes:
  - locating them on the filesystem
  - loading them from files
  - substituting placeholder values (e.g., `{{PROJECT}}`) with real ones

**Comment by oubiwann** [comment]
There are functions that now handle basic template loading, subst., etc..

That was done in 2f03998.

At this point, I think the general architecture is figured out. The rest of the architecture is more internal (e.g., how are commands going to be discovered, mapped to plugins, etc.).

**Comment by unbalancedparentheses** [comment]
Hey, could I know why you decided to remove some bash code and replace it by lfe? Thanks

**Comment by oubiwann** [comment]
Sure thing -- not just some bash, though -- all bash. Version 2.x will have no shell scripts or shell-script-generating code anywhere in it. It will be 100% LFE. Well, the one possible exception might be a short bootstrapping script ...

Version 1.x of `lfetool` is 100% shell. New features won't land there, but if you don't need anything new and prefer a shell script, that won't be going away :-)

The problems with the existing shell script are the following:
- people want to support many shells, not just bash
- unit testing is cumbersome at best (horrible at worst)
- which features get added with which shell support is getting harder and harder to track
- people's changes are starting to conflict (with some parts of `lfetool` supporting one shell, and others a different shell)
- due to the need to generate files from a single shell script, `lfetool` embeds base64-encoded files in the script itself; this makes it harder for new devs to make contributions (there is extensive documentation on how to develop plugins for `lfetool`, but it's hard to read and many contributors have missed this).

The benefits of moving to LFE are:
- we no longer have to worry about which shell is supported (with the possible small exception of a bootstrapping script)
- unit testing is a breeze
- feature changes will be easier to track/perform impact analysis on, etc.
- files will no longer be embedded; we'll be removing 1 to 2 layers of abstraction for contributing developers to deal with :-)
- it will be easier and quicker to add new features (I've already experienced this benefit myself, using the new version!)
- it will be possible, easy, and compelling for @rvirding to include `lfetool` in LFE itself, which would take care of any bootstrapping problems (or fully minimize them).
- we will be able to more easily provide an lfetool shell where one can perform many lfetool operations at once, if so desired
- last but not least, it's nice for a language's tools to be written in that language itself -- makes for a self-supporting development community

Downsides to using LFE instead of bash:
- commands will definitely run more slowly
- depending upon how a bootstrapping script is developed, getting started may involve more steps
- LFE will be required to be compiled and linked/installed to run any command (however, in a bootstrap script, some commands will be available without the need for LFE to be installed)

I've been using Version 2.0 from the command line, and though it is noticeably slower, it's not prohibitively slower (there's a pause, but not enough to make using the tool frustrating).  Running multiples of commands will be slower, but Version 2.x will eventually support an lfetool shell -- and that will be the recommended way to execute multiple commands (one-time Erlang start-up penalty, and then everything else should be super-quick).

**Comment by unbalancedparentheses** [comment]
Thanks @oubiwann for taking the time to answer. Even if I have never created a similar tool, I think it is a good idea to move away from bash. I am trying to understand everything, since I am really interested on copying your ideas to create an erltool that uses erlang.mk (I am not a big fan of rebar) to setup projects.

Again, thanks for commenting everyhing you do on github issues, even if there are not yet that many persons commiting to the project yet. It is very useful for those who want to understand it.

**Comment by oubiwann** [comment]
@pyotrgalois Great to hear! (all of it :-) ).

The part over `lfetool` v2 that I'm actually most excited about is supporting user plugins in `~/.lfetool/plugins/<name>/*.lfe`. This is going to make customizing the tool pretty easy. Also, customizing workflow/daily tasks/automation/etc. is one of the great entry points for people learning new languages. If we can offer a way to use the language while accomplishing some of these tasks, we've just won new hearts :-) (Whether that be Erlang or LFE.)

Keep us posted on your progress!

**Comment by blt** [comment]
> Sure thing -- not just some bash, though -- all bash. Version 2.x will have no shell scripts or shell-script-generating code anywhere in it. It will be 100% LFE. Well, the one possible exception might be a short bootstrapping script ...

I'm hard pressed to believe that you'll be able to get away from bash here--or cross-platform C, etc etc--but if you can write the bootstrap in LFE as well, I'll buy you dinner. :)

**Comment by oubiwann** [comment]
@blt If we end up including lfetool as part of LFE proper, `lfetool` will be built when compiling LFE. For that scenario, the "bootstrapping" is the usual BEAM language process: download and compile.

I suspect that even if we do include lfetool in LFE, I won't be able to resist providing a secondary `lein`-like approach: a small shell script that can get a user started from nothing + script download to kerl + Erlang + LFE + lfetool in one go. The number of commands that the bootstrap shell script will have to support will be fairly limited (download kerl, install kerl, install Erlang, install LFE, install lfetool) compared to the rest of lfetool.

We shall see...

**Comment by etnt** [comment]
Hm...I'm missing the proverbial "like button" here :-)

**Comment by oubiwann** [comment]
In my book, one proverbial "like" from Torbjörn is worth a legion of them on Facebook ;-)
